"""V0.5 training entry-point contract.

The V0.1 deliverable intentionally stops before choosing a neural framework.  This
module validates replay data and prints the tensors/data contracts a Policy + Value
trainer will consume.
"""

from __future__ import annotations

import argparse

from env.state_encoder import FlatStateEncoder
from training.replay_buffer import ReplayBuffer


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("replay", help="JSONL replay file generated by main.py --replay")
    args = parser.parse_args()
    buffer = ReplayBuffer.load_jsonl(args.replay)
    encoder = FlatStateEncoder()
    dimensions = {len(encoder.encode(sample.observation)) for sample in buffer.samples}
    outcomes = {sample.outcome for sample in buffer.samples}
    print(f"samples={len(buffer.samples)} state_dimensions={sorted(dimensions)} outcomes={sorted(outcomes)}")
    print("Replay contract is valid. Implement the V0.5 Transformer/Policy/Value trainer here.")


if __name__ == "__main__":
    main()
